#!/usr/bin/env python3
"""Emit the versioned NA=1 GPU FFT acceptance fixture from the independent oracle.

This script deliberately imports only ``periodic_ewald_reference.py``.  It
does not invoke UppASD, Builder A, a GPU, or directConvolution.  The checked-in
header is regenerated intentionally and reviewed as oracle data, not produced
during CTest.
"""
from __future__ import annotations

from periodic_ewald_reference import cell_vector, evaluate_converged


CASES = (
    ("cubic_1x1x1", (1, 1, 1),
     ((3.0, 0.0, 0.0), (0.0, 3.0, 0.0), (0.0, 0.0, 3.0)),
     (((1.0, -0.2, 0.4),),)),
    ("axial_2x1x1", (2, 1, 1),
     ((6.0, 0.0, 0.0), (0.0, 3.0, 0.0), (0.0, 0.0, 3.0)),
     (((1.0, -0.2, 0.4), (-0.3, 0.8, 0.1)),)),
    ("noncubic_2x3x1", (2, 3, 1),
     ((6.0, 0.0, 0.0), (0.0, 9.0, 0.0), (0.0, 0.0, 3.0)),
     (((0.20, -0.40, 0.10), (0.23, -0.38, 0.09),
       (0.26, -0.36, 0.08), (0.29, -0.34, 0.07),
       (0.32, -0.32, 0.06), (0.35, -0.30, 0.05)),)),
    # h[1]=0.45 and h[5]=0.35 intentionally differ.  The legacy h[5]
    # cofactor typo cannot pass the reciprocal identity for this fixture.
    ("genuinely_skew_2x1x1", (2, 1, 1),
     ((6.0, 0.45, 0.25), (0.8, 3.0, 0.35), (0.3, 0.2, 3.4)),
     (((1.0, -0.2, 0.4), (-0.3, 0.8, 0.1)),)),
    ("noncubic_2x3x1_m4", (2, 3, 1),
     ((6.0, 0.0, 0.0), (0.0, 9.0, 0.0), (0.0, 0.0, 3.0)),
     (((0.20, -0.40, 0.10), (0.23, -0.38, 0.09),
       (0.26, -0.36, 0.08), (0.29, -0.34, 0.07),
       (0.32, -0.32, 0.06), (0.35, -0.30, 0.05)),
      ((-0.20, 0.40, -0.10), (-0.23, 0.38, -0.09),
       (-0.26, 0.36, -0.08), (-0.29, 0.34, -0.07),
       (-0.32, 0.32, -0.06), (-0.35, 0.30, -0.05)),
      ((0.11, 0.07, -0.35), (0.13, 0.04, -0.31),
       (0.17, -0.02, -0.27), (0.19, -0.08, -0.23),
       (0.23, -0.14, -0.19), (0.29, -0.21, -0.13)),
      ((-0.41, 0.12, 0.03), (-0.37, 0.09, 0.08),
       (-0.31, 0.04, 0.14), (-0.24, -0.02, 0.19),
       (-0.18, -0.09, 0.22), (-0.12, -0.15, 0.27)))),
)


def positions(grid, cell):
    # C++/GPU contract: n1 fastest, then n2, then n3.
    return tuple(cell_vector(cell, (x / grid[0], y / grid[1], z / grid[2]))
                 for z in range(grid[2]) for y in range(grid[1]) for x in range(grid[0]))


def literal(value: float) -> str:
    return f"{value:.17g}"


def main() -> None:
    print("// Generated by generate_gpu_ewald_goldens.py; DO NOT edit by hand.")
    print("// Oracle: periodic_ewald_reference.evaluate_converged, tol=1e-13, max_shell=16.")
    print("#pragma once\n\n#include <array>\n#include <cstddef>\n\nnamespace gpu_ewald_golden_v1 {\n")
    print("struct Case { const char* name; std::array<std::size_t, 3> grid; std::array<double, 9> H; std::size_t ensembles; const double* moments; const double* fields; const double* energies; };\n")
    entries = []
    for number, (name, grid, cell, ensemble_moments) in enumerate(CASES):
        all_fields = []
        energies = []
        for moments in ensemble_moments:
            result = evaluate_converged(positions(grid, cell), moments, cell, tolerance=1e-13, max_shell=16)
            all_fields.extend(component for field in result.fields for component in field)
            energies.append(result.energy)
        moments_flat = [component for ensemble in ensemble_moments for moment in ensemble for component in moment]
        h_flat = [component for vector in cell for component in vector]
        print(f"inline constexpr std::array<double, {len(h_flat)}> h_{number}{{{{{', '.join(map(literal, h_flat))}}}}};")
        print(f"inline constexpr std::array<double, {len(moments_flat)}> moments_{number}{{{{{', '.join(map(literal, moments_flat))}}}}};")
        print(f"inline constexpr std::array<double, {len(all_fields)}> fields_{number}{{{{{', '.join(map(literal, all_fields))}}}}};")
        print(f"inline constexpr std::array<double, {len(energies)}> energies_{number}{{{{{', '.join(map(literal, energies))}}}}};\n")
        entries.append((name, grid, len(ensemble_moments), number))
    print("inline constexpr std::array<Case, %d> cases{" % len(entries))
    for name, grid, ensembles, number in entries:
        print(f'   Case{{"{name}", {{{grid[0]}, {grid[1]}, {grid[2]}}}, h_{number}, {ensembles}, moments_{number}.data(), fields_{number}.data(), energies_{number}.data()}},')
    print("};\n} // namespace gpu_ewald_golden_v1")


if __name__ == "__main__":
    main()
