#!/usr/bin/env python3
"""Generate NA=2 GPU FFT acceptance data from the independent Ewald oracle.

This deliberately distorted L1_0-style pair exercises basis phases as well
as the full triclinic reciprocal geometry.  It must not import UppASD, the
host Builder A, or any GPU code.
"""
from __future__ import annotations

from periodic_ewald_reference import cell_vector, evaluate_converged


CASES = (
    ("l10_tetragonal_1x1x1", (1, 1, 1),
     ((3.8, 0.0, 0.0), (0.0, 3.8, 0.0), (0.0, 0.0, 5.2)),
     ((0.0, 0.0, 0.0), (1.9, 1.9, 2.6)),
     (((1.0, -0.2, 0.4), (-0.3, 0.8, 0.1)),)),
    ("l10_distorted_skew_2x1x1_m4", (2, 1, 1),
     ((7.6, 0.45, 0.2), (0.7, 3.7, 0.25), (0.3, 0.2, 5.3)),
     ((0.0, 0.0, 0.0), (1.95, 1.65, 2.55)),
     (((0.20, -0.40, 0.10), (-0.30, 0.80, 0.10),
       (0.26, -0.36, 0.08), (0.19, -0.08, -0.23)),
      ((-0.20, 0.40, -0.10), (0.30, -0.80, -0.10),
       (-0.26, 0.36, -0.08), (-0.19, 0.08, 0.23)),
      ((0.11, 0.07, -0.35), (0.13, 0.04, -0.31),
       (0.17, -0.02, -0.27), (0.19, -0.08, -0.23)),
      ((-0.41, 0.12, 0.03), (-0.37, 0.09, 0.08),
       (-0.31, 0.04, 0.14), (-0.24, -0.02, 0.19)))),
)


def positions(grid, cell, basis):
    return tuple(
        tuple(cell_vector(cell, (x / grid[0], y / grid[1], z / grid[2]))[axis] + offset[axis]
              for axis in range(3))
        for z in range(grid[2]) for y in range(grid[1]) for x in range(grid[0])
        for offset in basis)


def literal(value: float) -> str:
    return f"{value:.17g}"


def values(values):
    return ", ".join(map(literal, values))


def main() -> None:
    print("// Generated by generate_gpu_ewald_multibasis_goldens.py; DO NOT edit by hand.")
    print("// Oracle: periodic_ewald_reference.evaluate_converged, tol=1e-13, max_shell=16.")
    print("#pragma once\n\n#include <array>\n#include <cstddef>\n\nnamespace gpu_ewald_multibasis_golden_v1 {\n")
    print("struct Case { const char* name; std::array<std::size_t, 3> grid; std::array<double, 9> H; std::size_t basis; const double* offsets; std::size_t ensembles; const double* moments; const double* fields; const double* energies; };\n")
    entries = []
    for number, (name, grid, cell, basis, ensemble_moments) in enumerate(CASES):
        all_fields, energies = [], []
        positions_for_case = positions(grid, cell, basis)
        for moments in ensemble_moments:
            result = evaluate_converged(positions_for_case, moments, cell, tolerance=1e-13, max_shell=16)
            all_fields.extend(component for field in result.fields for component in field)
            energies.append(result.energy)
        print(f"inline constexpr std::array<double, 9> h_{number}{{{{{values(component for vector in cell for component in vector)}}}}};")
        print(f"inline constexpr std::array<double, {3 * len(basis)}> offsets_{number}{{{{{values(component for offset in basis for component in offset)}}}}};")
        flat_moments = [component for ensemble in ensemble_moments for moment in ensemble for component in moment]
        print(f"inline constexpr std::array<double, {len(flat_moments)}> moments_{number}{{{{{values(flat_moments)}}}}};")
        print(f"inline constexpr std::array<double, {len(all_fields)}> fields_{number}{{{{{values(all_fields)}}}}};")
        print(f"inline constexpr std::array<double, {len(energies)}> energies_{number}{{{{{values(energies)}}}}};\n")
        entries.append((name, grid, len(basis), len(ensemble_moments), number))
    print("inline constexpr std::array<Case, %d> cases{" % len(entries))
    for name, grid, basis, ensembles, number in entries:
        print(f'   Case{{"{name}", {{{grid[0]}, {grid[1]}, {grid[2]}}}, h_{number}, {basis}, offsets_{number}.data(), {ensembles}, moments_{number}.data(), fields_{number}.data(), energies_{number}.data()}},')
    print("};\n} // namespace gpu_ewald_multibasis_golden_v1")


if __name__ == "__main__":
    main()
