#!/usr/bin/env python3
"""RCG-04D: E2E-MOVING-OFF-FINE.

Establishes nonvacuous moving-state parity between the ordinary
(AdaptiveCG-disabled) feature-off production path and the AdaptiveCG
all-fine (``cg_mask_mode STATIC``, no mask file) path, starting from a
genuinely nonstationary (nonzero-torque) conical-spiral state -- not the
uniform, stationary state the existing ``feature_off``/``static_all_fine``
pair uses (that pair is retained unmodified as a zero-torque smoke test; see
``fixture_dependencies.py``).

Fixtures: ``e2e/moving_feature_off`` and ``e2e/moving_all_fine``, both
consuming a byte-identical ``momfile`` generated by
``moving_state_generator.conical_spiral_state`` (parameters recorded in each
fixture's ``GENERATOR_MANIFEST.json`` and reproduced as ``GENERATOR_PARAMS``
below). See each fixture's ``README.md`` for full provenance and the exact
production defect this slice found and fixed
(``source/CoarseGraining/adaptivecgproduction.f90:adaptive_cg_cpu_step`` was
missing the physical gyromagnetic-ratio constant ``gama`` for the atomistic
fine-region LLG update, silently freezing any genuinely moving all-fine
state while leaving every existing uniform/zero-torque fixture unaffected).

Provisional fp64 tolerances below are derived from the observed error
between two independent Heun-family integrator implementations of the same
physics (production's ``evolve_first``/``smodeulermpt`` for feature-off vs.
``adaptive_cg_cpu_step``'s own predictor-corrector for all-fine), not fitted
to make the test pass: see the RCG-04D evidence document for the exact
observed values and the headroom multiplier chosen for each. Final
cross-precision (fp32/backend) budgets are explicitly out of scope --
RCG-04I's responsibility.
"""

from __future__ import annotations

import argparse
import dataclasses
import hashlib
import math
import subprocess
from pathlib import Path

from fixture_dependencies import MOVING_ALL_FINE_CASE, MOVING_FEATURE_OFF_CASE
from moving_state_generator import Geometry, conical_spiral_state
import torque_oracle as orc
import trajectory_evidence as te

ROOT = Path(__file__).with_name("e2e")

GEOMETRY = Geometry(na=2, n1=6, n2=2, n3=2, basis=((0.0, 0.0, 0.0), (0.5, 0.5, 0.5)))
GENERATOR_PARAMS = dict(
    cone_angle_deg=40.0, turns=1, axis=(0.0, 0.0, 1.0), phase_deg=0.0,
    modulation_cell_axis=0, moment_magnitude=2.23, landeg=2.0,
)
OFF_SIMID = "cg104mvo"
FINE_SIMID = "cg104mva"

# Nontriviality floors (oracle-computed, independent of production): observed
# values on this fixture are max_torque=rms_torque~0.672 (uniform across
# atoms for an exact conical-spiral ansatz -- see torque_oracle.py's module
# docstring), max_field_misalignment_deg~3.17. Floors are set roughly an
# order of magnitude below the observed values.
MIN_MAX_TORQUE = 0.05
MIN_RMS_TORQUE = 0.05
MIN_FIELD_MISALIGNMENT_DEG = 0.5
MIN_DISPLACEMENT_RAD = 0.02  # observed final displacement ~0.124 rad (~7.1 deg)

# Provisional fp64 parity budgets (Human review pending; see evidence doc).
# Observed on this fixture: angular max=5.77e-5 rad / rms=3.41e-5 rad,
# component max_abs=5.57e-5 / rms=1.97e-5, restart max_abs=5.57e-5,
# independent-oracle energy max_abs=3.24e-4 (energy scale ~584, i.e. ~5.5e-7
# relative). Budgets below give roughly an order of magnitude of headroom.
MAX_ANGULAR_ERROR_RAD = 5.0e-4
MAX_COMPONENT_ERROR = 5.0e-4
MAX_RESTART_ERROR = 5.0e-4
MAX_ENERGY_ERROR_J_REDUCED = 2.0e-3


class NegativeControlDidNotFailError(AssertionError):
    """Raised when a deliberately broken trajectory pair passed the parity check anyway."""


def run_case(binary: Path, case: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [str(binary)], cwd=case, text=True,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=60, check=False,
    )


def verify_byte_identical_initial_state(off_dir: Path, fine_dir: Path) -> None:
    off_bytes = (off_dir / "momfile").read_bytes()
    fine_bytes = (fine_dir / "momfile").read_bytes()
    assert off_bytes == fine_bytes, (
        "feature-off and all-fine momfile are not byte-identical: "
        f"{off_dir/'momfile'} vs {fine_dir/'momfile'}"
    )
    assert hashlib.sha256(off_bytes).hexdigest() == hashlib.sha256(fine_bytes).hexdigest()


def verify_normalized_inputs_equal(off_dir: Path, fine_dir: Path) -> dict[str, str]:
    """Compare normalized inpsd.dat records, not the raw text (which legitimately differs).

    The two ``inpsd.dat`` files intentionally differ in exactly the
    AdaptiveCG block (``do_adaptive_cg``/``block_size_*``/``cg_*``) and
    ``simid``; every other physically/numerically relevant key must match
    exactly. Comparing raw file text would either be too strict (simid must
    differ for output files not to collide) or require the reviewer to trust
    a "looks similar" reading, which the RCG-04D governing rules explicitly
    reject.
    """
    ignored_keys = {"simid", "do_adaptive_cg", "block_size_x", "block_size_y",
                     "block_size_z", "cg_operator", "cg_mask_mode", "cg_diagnostics"}
    def normalized(path: Path) -> dict[str, str]:
        records: dict[str, str] = {}
        for line in path.read_text().splitlines():
            fields = line.split()
            if not fields or fields[0] in ("cell",) or fields[0].replace(".", "").replace(
                    "-", "").isdigit():
                continue
            key = fields[0]
            value = " ".join(fields[1:])
            if key not in ignored_keys:
                records[key] = value
        return records

    off_records = normalized(off_dir / "inpsd.dat")
    fine_records = normalized(fine_dir / "inpsd.dat")
    mismatched = {
        key: (off_records.get(key), fine_records.get(key))
        for key in set(off_records) | set(fine_records)
        if off_records.get(key) != fine_records.get(key)
    }
    assert not mismatched, (
        "feature-off/all-fine inpsd.dat differ in a physically/numerically "
        f"relevant key beyond the intended AdaptiveCG block: {mismatched}"
    )
    return off_records


def compute_independent_nontriviality() -> orc.TorqueReport:
    """RCG-04D governing rule: initial torque computed independently of production."""
    state = conical_spiral_state(GEOMETRY, **GENERATOR_PARAMS)
    shells = orc.parse_jfile_shells((ROOT / "jfile").read_text())
    return orc.initial_torque_report(GEOMETRY, shells, state.direction_by_atom)


def independent_energy_series(trajectory: te.Trajectory,
                               shells: tuple[orc.ExchangeShell, ...]) -> dict[int, float]:
    """Named-energy comparison using the RCG-04D oracle, not either production diagnostic.

    Applied identically to both trajectories (see main()), this sidesteps
    reconciling the ordinary path's ``totenergy.<simid>.out`` and
    AdaptiveCG's ``last_energy_j`` diagnostics, which this slice's
    calibration work (torque_oracle.py's module docstring) found use two
    different internal unit/normalization conventions that were not fully
    reconciled from source alone. The single-sample AdaptiveCG
    ``last_energy_j``/``last_field_checksums_t`` diagnostic is still
    additionally checked below (production's own reused output, per the
    governing "prefer existing production output" rule) but only as
    supplementary evidence: RCG-04C already recorded that this diagnostic
    fires once per run (final step only), not per sampled step.
    """
    energies: dict[int, float] = {}
    for step in trajectory.step_numbers():
        directions = {
            atom: record.direction
            for (ensemble, atom), record in trajectory.step(step).records.items()
        }
        per_atom = orc.exchange_energy_per_atom(GEOMETRY, shells, directions)
        energies[step] = sum(per_atom.values())
    return energies


def _mutate_freeze(trajectory: te.Trajectory) -> te.Trajectory:
    """Negative control: every step frozen to the initial state (the real defect this slice fixed)."""
    initial = trajectory.steps[0]
    frozen_steps = tuple(
        dataclasses.replace(step, records=initial.records) for step in trajectory.steps
    )
    return dataclasses.replace(trajectory, steps=frozen_steps)


def _mutate_drop_step(trajectory: te.Trajectory) -> te.Trajectory:
    """Negative control: one interior sampled step is missing."""
    assert len(trajectory.steps) > 2
    kept = trajectory.steps[:1] + trajectory.steps[2:]
    return dataclasses.replace(trajectory, steps=kept)


def _mutate_perturb_one_component(trajectory: te.Trajectory) -> te.Trajectory:
    """Negative control: one spin component at the final step is corrupted."""
    steps = list(trajectory.steps)
    final = steps[-1]
    key = next(iter(final.records))
    record = final.records[key]
    corrupted_direction = (record.direction[0] + 0.5, record.direction[1], record.direction[2])
    new_records = dict(final.records)
    new_records[key] = dataclasses.replace(record, direction=corrupted_direction)
    steps[-1] = dataclasses.replace(final, records=new_records)
    return dataclasses.replace(trajectory, steps=tuple(steps))


def run_negative_controls(off_traj: te.Trajectory, fine_traj: te.Trajectory) -> None:
    """Prove the parity assertions above are defect-sensitive, not vacuous.

    Every mutation here is applied to an in-memory, already-parsed
    ``Trajectory`` object (frozen dataclasses, rebuilt via
    ``dataclasses.replace``); no tracked file is ever written, so there is
    nothing to restore afterward -- the next call to this script re-parses
    the real, unmodified production output from disk.
    """
    frozen = _mutate_freeze(fine_traj)
    frozen_error = te.angular_trajectory_error(off_traj, frozen)
    if frozen_error.max_radians <= MAX_ANGULAR_ERROR_RAD:
        raise NegativeControlDidNotFailError(
            f"frozen-evolution negative control did not fail: max_radians="
            f"{frozen_error.max_radians} <= budget {MAX_ANGULAR_ERROR_RAD}"
        )
    print(
        f"negative control [freeze]: max_radians={frozen_error.max_radians:.6g} "
        f"> budget {MAX_ANGULAR_ERROR_RAD:.1e} -- failed as expected "
        "(this is the exact defect this slice found and fixed)"
    )

    dropped = _mutate_drop_step(fine_traj)
    try:
        te.angular_trajectory_error(off_traj, dropped)
    except te.TrajectoryKeyMismatchError:
        print("negative control [drop-step]: TrajectoryKeyMismatchError raised as expected")
    else:
        raise NegativeControlDidNotFailError(
            "drop-step negative control did not fail: comparison silently accepted "
            "trajectories with mismatched (step, ensemble, atom) keys"
        )

    perturbed = _mutate_perturb_one_component(fine_traj)
    perturbed_error = te.angular_trajectory_error(off_traj, perturbed)
    if perturbed_error.max_radians <= MAX_ANGULAR_ERROR_RAD:
        raise NegativeControlDidNotFailError(
            f"single-component-perturbation negative control did not fail: max_radians="
            f"{perturbed_error.max_radians} <= budget {MAX_ANGULAR_ERROR_RAD}"
        )
    print(
        f"negative control [perturb-one-component]: max_radians={perturbed_error.max_radians:.6g} "
        f"> budget {MAX_ANGULAR_ERROR_RAD:.1e} -- failed as expected"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--binary", type=Path, required=True)
    args = parser.parse_args()
    binary = args.binary.resolve()

    off_dir = ROOT / MOVING_FEATURE_OFF_CASE
    fine_dir = ROOT / MOVING_ALL_FINE_CASE

    # --- Input equivalence (governing rule: prove with normalized manifests,
    # not visual inpsd.dat resemblance) ---
    verify_byte_identical_initial_state(off_dir, fine_dir)
    verify_normalized_inputs_equal(off_dir, fine_dir)
    print("input equivalence: momfile byte-identical; inpsd.dat records equal apart "
          "from the intended AdaptiveCG block")

    # --- Independent pre-acceptance nontriviality gate ---
    report = compute_independent_nontriviality()
    assert report.max_torque > MIN_MAX_TORQUE, (
        f"oracle max_torque={report.max_torque} does not exceed nontriviality floor "
        f"{MIN_MAX_TORQUE}; this state would be a stationary special case"
    )
    assert report.rms_torque > MIN_RMS_TORQUE
    assert report.max_field_misalignment_deg > MIN_FIELD_MISALIGNMENT_DEG, (
        f"oracle max_field_misalignment_deg={report.max_field_misalignment_deg} does not "
        f"exceed {MIN_FIELD_MISALIGNMENT_DEG}; effective field is (near-)parallel to the "
        "local spin everywhere, i.e. an (approximate) stationary state"
    )
    print(
        f"independent oracle: max_torque={report.max_torque:.6g} "
        f"rms_torque={report.rms_torque:.6g} "
        f"max_field_misalignment_deg={report.max_field_misalignment_deg:.6g} "
        "-- state is demonstrably not a stationary special case"
    )

    # --- Run both production cases through the real executable ---
    off_result = run_case(binary, off_dir)
    assert off_result.returncode == 0, off_result.stdout
    assert "AdaptiveCG:" not in off_result.stdout, off_result.stdout

    fine_result = run_case(binary, fine_dir)
    assert fine_result.returncode == 0, fine_result.stdout
    assert "AdaptiveCG: capability accepted" in fine_result.stdout, fine_result.stdout

    # --- Complete per-spin fp64 trajectory comparison ---
    off_traj = te.load_moment_trajectory(off_dir, simid=OFF_SIMID)
    fine_traj = te.load_moment_trajectory(fine_dir, simid=FINE_SIMID)
    assert off_traj.step_numbers() == fine_traj.step_numbers()

    off_displacement = te.spin_displacement(off_traj)
    fine_displacement = te.spin_displacement(fine_traj)
    assert off_displacement.max_final_displacement > MIN_DISPLACEMENT_RAD, (
        f"feature-off max_final_displacement={off_displacement.max_final_displacement} "
        f"does not exceed floor {MIN_DISPLACEMENT_RAD}"
    )
    assert fine_displacement.max_final_displacement > MIN_DISPLACEMENT_RAD, (
        f"all-fine max_final_displacement={fine_displacement.max_final_displacement} "
        f"does not exceed floor {MIN_DISPLACEMENT_RAD}"
    )
    print(
        f"displacement: feature-off={off_displacement.max_final_displacement:.6g} rad, "
        f"all-fine={fine_displacement.max_final_displacement:.6g} rad "
        f"(both exceed floor {MIN_DISPLACEMENT_RAD})"
    )

    component = te.component_trajectory_error(off_traj, fine_traj)
    angular = te.angular_trajectory_error(off_traj, fine_traj)
    assert component.max_abs_error_overall <= MAX_COMPONENT_ERROR, component.as_dict()
    assert angular.max_radians <= MAX_ANGULAR_ERROR_RAD, angular.as_dict()
    print(
        f"trajectory parity: component max_abs={component.max_abs_error_overall:.6g} "
        f"rms={component.rms_error_overall:.6g}; angular max={angular.max_radians:.6g} rad "
        f"({math.degrees(angular.max_radians):.6g} deg) "
        f"rms={angular.rms_radians:.6g} rad over {angular.sample_count} samples"
    )

    # --- Restart-state comparison ---
    off_restart = te.load_restart_state(off_dir)
    fine_restart = te.load_restart_state(fine_dir)
    restart_component = te.component_trajectory_error(off_restart, fine_restart)
    assert restart_component.max_abs_error_overall <= MAX_RESTART_ERROR, restart_component.as_dict()
    print(f"restart-state parity: max_abs={restart_component.max_abs_error_overall:.6g}")

    # --- Named energy comparison (independent oracle, every sampled step) ---
    shells = orc.parse_jfile_shells((ROOT / "jfile").read_text())
    off_energy = independent_energy_series(off_traj, shells)
    fine_energy = independent_energy_series(fine_traj, shells)
    assert set(off_energy) == set(fine_energy)
    max_energy_error = max(abs(off_energy[step] - fine_energy[step]) for step in off_energy)
    assert max_energy_error <= MAX_ENERGY_ERROR_J_REDUCED, (
        f"independent-oracle exchange energy max abs error {max_energy_error} exceeds "
        f"budget {MAX_ENERGY_ERROR_J_REDUCED}"
    )
    print(
        f"named energy (independent oracle, exchange, every sampled step): "
        f"max abs error={max_energy_error:.6g} (energy scale ~{abs(off_energy[0]):.4g})"
    )

    # --- Production's own single-sample energy/field diagnostic (supplementary) ---
    fine_series = te.parse_energy_field_series(fine_result.stdout)
    assert len(fine_series) == 1, (
        "expected exactly one AdaptiveCG last_energy_j emission (RCG-04C: production "
        f"emits this diagnostic once, at the final step); got {len(fine_series)}"
    )
    assert fine_series[0].energies_j["atomistic_bilinear"] != 0.0
    assert fine_series[0].field_checksums_t["atom_norm2"] > 0.0
    print(
        "production last_energy_j/last_field_checksums_t (final step only, RCG-04C "
        f"limitation): atomistic_bilinear={fine_series[0].energies_j['atomistic_bilinear']:.6g} J"
    )

    # --- Defect sensitivity: prove the checks above are not vacuous ---
    run_negative_controls(off_traj, fine_traj)

    print("RCG-04D E2E-MOVING-OFF-FINE passed")


if __name__ == "__main__":
    main()
