name: Build wheels on Windows (alt)

#on: [release]
on: [release, push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        #os: [ubuntu-20.04, macOS-11]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Provide fftw, ninja  (macOS)
        if: runner.os == 'macOS'
        run: |
          # fftw3 
          brew install fftw ninja meson
          fftw-wisdom -V

      - name: Provide ninja  (linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y install ninja-build meson openblas-dev liblapack-dev

      - name: Provide gfortran (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: inherit
          install: >-
            git
            make

          pacboy: >-
            toolchain:p
            gcc-fortran:p
            openblas:p
            lapack:p
            fftw:p
            cmake:p
            ninja:p

      - name: Tell distutils to use mingw (Windows)
        if: runner.os == 'Windows'
        run: |
           #echo "[build]`ncompiler=mingw32" | Out-File -Encoding ASCII ~/pydistutils.cfg
           echo "[build]`ncompiler=mingw32" 

      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        #run: python -m pip install cibuildwheel==2.10.1
        run: python -m pip install cibuildwheel ninja numpy scipy

      - name: Build wheels
        run: 
          python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value
        env:
          CIBW_SKIP: cp36* pp38-manylinux* pp39* pp31* cp38-manylinux_i686 
          CIBW_ENVIRONMENT_WINDOWS: CC=gcc CXX=g++ FC=gfortran
          CIBW_ENVIRONMENT_MACOS: CC=gcc-13 CXX=g++-13 FC=gfortran-13
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
          #FC: gfortran
          #CC: gcc

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build
        run: python -m pip install build wheel setuptools

      - name: Build source distribution
        run: python -m build . --sdist

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz

