name: Build wheels on Linux

on: [release]
#on: [release, push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.10.1

      - name: Build wheels
        run: 
          python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value
        env:
          CIBW_SKIP: cp36* cp37* pp38-manylinux* pp39* pp31* cp38-manylinux_i686 cp*-musllinux*
          CIBW_ENVIRONMENT_WINDOWS: CC=gcc CXX=g++ FC=gfortran
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
          FC: gfortran
          CC: gcc

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install needed pip packages
        run: python -m pip install build wheel

      - name: Build source distribution
        run: python -m build . --sdist

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz
