name: Build wheels on MacOS

#on: [release]
on: [release, push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [macos-13]
        #os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - name: Provide packages (macOS)
        if: runner.os == 'macOS'
        run: |
          # fftw3 
          brew install fftw
          fftw-wisdom -V
          # ninja
          brew install ninja
          # meson
          brew install meson

      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: 
          python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value
        env:
          CIBW_SKIP: cp36* cp37* pp38-manylinux* pp39* pp31* cp38-manylinux_i686 
          CIBW_ENVIRONMENT_WINDOWS: CC=gcc CXX=g++ FC=gfortran
          CIBW_ENVIRONMENT_MACOS: CC=gcc-13 CXX=g++-13 FC=gfortran-13
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
          FC: gfortran-13
          CC: gcc-13



      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

