name: Build binaries on Windows

on:
  #push:
  release:
  #pull_request:
  #workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟦', sys: mingw64, arch: x86_64 }
          - { icon: '🟨', sys: ucrt64,  arch: x86_64  } # Experimental!
          #- { icon: '🟧', sys: clang64, arch: x86_64 } # Experimental!
          #- { icon: '⬛', sys: mingw32, arch: i686 } # Disabled
    name: 🚧 ${{ matrix.icon }} ${{ matrix.sys }}
    continue-on-error: true
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2 gcc'
      if: ${{ matrix.sys != 'clang64' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make

        pacboy: >-
          toolchain:p
          gcc-fortran:p
          openblas:p
          lapack:p
          fftw:p
          cmake:p
          ninja:p
          
    - name: '${{ matrix.icon }} Setup MSYS2 clang'
      if: ${{ matrix.sys == 'clang64' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make

        pacboy: >-
          toolchain:p
          flang:p
          openblas:p
          lapack:p
          fftw:p
          cmake:p
          ninja:p

          
    - name: '🚧 Build TOOL'
      run: |
        cmake -S . -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build 
        ls build/bin
        cp build/bin/sd.gfortran.exe build/bin/sd.gfortran.${{matrix.sys}}.${{matrix.arch}}.exe
        cp build/bin/sd.gfortran.exe build/bin/uppasd.${{matrix.sys}}.${{matrix.arch}}.exe
        ls build/bin
        
    - uses: actions/upload-artifact@v4
      with:
      name: uppasd.${{matrix.sys}}.${{matrix.arch}}
      path: build/bin/uppasd*.exe
